services:
  db:
    image: postgres:15-alpine
    container_name: auction_db
    environment:
      POSTGRES_USER: auction_admin
      POSTGRES_PASSWORD: SuperSecretPassword123!
      POSTGRES_DB: AuctionSystemDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
